pipeline {
    agent any

    environment {
        IMAGE_NAME = "health-api:local"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'docker build -t %IMAGE_NAME% ./app'
            }
        }

        stage('Test') {
            steps {
                bat '''
                docker run --rm ^
                -v "%WORKSPACE%:/app" ^
                %IMAGE_NAME% ^
                python -m pytest --junitxml=/app/pytest.xml -q
                '''
            }
            post {
                always {
                    junit 'pytest.xml'
                }
            }
        }

        stage('Security Basic Check') {
            steps {
                bat 'echo "Placeholder: dependency validation step"'
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker compose down'
                bat 'docker compose up -d --build'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}